name: Build and Publish Docker Image

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t devops-homework .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-homework
  
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python
        run: sudo apt-get update -y && sudo apt-get install -y python3 python3-pip

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Setup snyk
        uses: snyk/actions/setup@master

      - name: Run snyk
        run: snyk test --file=src/requirements.txt
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}