name: Sonarcloud application workflow

on:
  push:
    branches:
      - main
    pull_request:
      types: [opened, synchronize]

jobs:
  sonarcloud:
    name: Sonarloud
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:`
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}